export enum ENV_KEY {
  APP_ENV = 'APP_ENV',
  MONGO_URI = 'MONGO_URI',

  AUDIT_ENDPOINT = 'AUDIT_ENDPOINT',
  AUDIT_USERNAME = 'AUDIT_USERNAME',
  AUDIT_PASSWORD = 'AUDIT_PASSWORD',

  BLOCKCHAIN_ENDPOINT = 'BLOCKCHAIN_ENDPOINT',

  CLIENT_JWT_SECRET = 'CLIENT_JWT_SECRET',
  CLIENT_JWT_EXPIRATION = 'CLIENT_JWT_EXPIRATION',

  SYSTEM_ADMIN_EMAIL = 'SYSTEM_ADMIN_EMAIL',
  SYSTEM_ADMIN_PASSWORD = 'SYSTEM_ADMIN_PASSWORD',

  GAME_ENDPOINT = 'GAME_ENDPOINT',
  GAME_API_KEY = 'GAME_API_KEY',
  GAME_API_SECRET = 'GAME_API_SECRET',

  DOMAIN = 'DOMAIN',

  USDT_TOKEN_ADDESS = 'USDT_TOKEN_ADDESS',
  MULTISIG_ADDRESS = 'MULTISIG_ADDRESS',

  WEBSOCKET_ENDPOINT = 'WEBSOCKET_ENDPOINT',
  WEBSOCKET_AUTH_SECRET = 'WEBSOCKET_AUTH_SECRET',

  IMAGE_SERVICE_ENDPOINT = 'IMAGE_SERVICE_ENDPOINT',

  KAFKA_IMG_PROCESSING_TOPIC_ID = 'KAFKA_IMG_PROCESSING_TOPIC_ID',
  KAFKA_IMG_PROCESS_RESULT_TOPIC_ID = 'KAFKA_IMG_PROCESS_RESULT_TOPIC_ID',
  KAFKA_BROKER_URL = 'KAFKA_BROKER_URL',
  KAFKA_CLIENT_ID = 'KAFKA_CLIENT_ID',
  KAFKA_CONSUMER_GROUP_ID = 'KAFKA_CONSUMER_GROUP_ID',

  SMTP_HOST = 'SMTP_HOST',
  SMTP_PORT = 'SMTP_PORT',
  SMTP_SECURE = 'SMTP_SECURE',
  SMTP_USERNAME = 'SMTP_USERNAME',
  SMTP_PASSWORD = 'SMTP_PASSWORD',
  SMTP_MAIL_FROM = 'SMTP_MAIL_FROM',

  APP_PUBLIC_URL = 'APP_PUBLIC_URL',

  AUGMENTLABS_SECRET_TOKEN = 'AUGMENTLABS_SECRET_TOKEN',
  AUGMENTLABS_MEMBER_API_URL = 'AUGMENTLABS_MEMBER_API_URL',
  AUGMENTLABS_MEMBER_API_SECRET = 'AUGMENTLABS_MEMBER_API_SECRET',
}

export enum REQUEST_HEADER {
  GAME_API_KEY = 'x-api-key',
  GAME_API_SECRET = 'x-api-secret',
  INTEGRATION_HEADER = 'x-integration-token',
}

export enum SHARES_TRADE_TYPE {
  NORMAL = 'normal',
  INVESTMENT = 'investment'
}

export enum ENTITY_STATUS {
  ACTIVE = 'active',
  SUSPENDED = 'suspended',
  INACTIVE = 'inactive',
}

export enum GAME_DEPOSIT_STATUS {
  FAILED = 'failed',
  PENDING = 'pending',
  SUBMITTED = 'submitted',
  INPROGRESS = 'inprogress',
  CREDITED = 'credited',
  REJECTED = 'rejected',
}

export enum GAME_DEPOSIT_STATUS_NUMBER {
  inprogress = 1,
  credited = 2,
  rejected = 3,
}

export enum GAME_WITHDRAW_STATUS {
  PENDING = 'pending',
  SUBMITTED = 'submitted',
  INPROGRESS = 'inprogress',
  APPROVED = 'approved',
  COMPLETED = 'completed',
  REJECTED = 'rejected',
  FAILED = 'failed',
}

export enum GAME_WITHDRAW_STATUS_NUMBER {
  inprogress = 1,
  approved = 2,
  completed = 3,
  rejected = 4,
  failed = 5,
}

export enum GAME_TRANSACTION_TYPE {
  DEPOSIT = 'deposit',
  WITHDRAW = 'withdraw',
}

export enum GAME_DEPOSIT_SORT_COLUMN {
  ADDON = 'addon',
  AMTTOINVEST = 'amttoinvest',
  STATUSID = 'statusid',
  ACTIONEDON = 'actionedon',
}

export enum GAME_WITHDRAW_SORT_COLUMN {
  WDON = 'wdon',
  WDAMT = 'wdamt',
  STATUSID = 'statusid',
  ACTIONEDON = 'actionedon',
}

export enum SYSTEM_USER_TYPE {
  MODERATOR = 'moderator',
  ADMIN = 'admin',
}

export enum CHAT_TYPE {
  SINGLE = 'single',
  GROUP = 'group',
}

export enum CHAT_MESSAGE_TYPE {
  SEND_MESSAGE = 'send_message',
  REPLY_MESSAGE = 'reply_message',
  READ_MESSAGE = 'read_message',
  DELETE_MESSAGE = 'delete_message',
  ACK_MESSAGE_RECEIVED = 'ack_message_received',
}

export const ERR_CODE = {
  USER_PIN_NOT_SET: 'USER_PIN_NOT_SET'.toLowerCase(),
  USER_LOCKED: 'USER_LOCKED'.toLowerCase(),
  INVALID_PIN: 'INVALID_PIN'.toLowerCase(),
  BAD_REQUEST: 'BAD_REQUEST'.toLowerCase(),
  CHAT_NOT_FOUND: 'CHAT_NOT_FOUND'.toLowerCase(),
  WITHDRAW_REQUEST_PENDING: 'You have a pending withdraw request. Please wait until it is approved to make another request',
  IMG_IS_NSFW: 'IMG_IS_NSFW'.toLowerCase(),
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'.toLowerCase(),
  INVALID_SIGNATURE: 'INVALID_SIGNATURE'.toLowerCase(),
  REFERENCE_ID_ALREADY_USED: 'REFERENCE_ID_ALREADY_USED'.toLowerCase(),
  INVALID_REFERENCE_ID: 'INVALID_REFERENCE_ID'.toLowerCase(),
};

export const RANDOM_USERS_TTL = 1000 * 60 * 5; // 5 minutes

export const MAX_PIN_FAILURE = 5;

export const DEFAULT_CACHE_TTL = 20000;
export const ANALYTIC_CACHE_TTL = 1800000;

export const MAX_SEND_EMAIL_RECORDS = 1;

export const DEFAULT_SHARE_PRICE = '0.03';
export const DEFAULT_TX_FEE = '0.025';
export const DEFAULT_BUY_LIMIT = 999999999;

export const INJECTION_TOKEN = {
  AUDIT_SERVICE: Symbol.for('AUDIT_SERVICE'),
  KAFKA_SERVICE: Symbol.for('KAFKA_SERVICE'),
  MAILER_SERVICE: Symbol.for('MAILER_SERVICE'),
};

export enum APP_EVENT {
  SHARE_BOUGHT = 'shares.bought',
  SHARE_SOLD = 'shares.sold',
  FUNDS_TRANSFERRED = 'funds.transferred',
  TOKEN_TRANSFERRED = 'token.transferred',
  EMAIL_UPDATED = 'email.updated',
  USER_UPDATED = 'user.updated',
  IMAGE_PROCESSED = 'image.processed',
  IMAGE_REJECTED = 'image.rejected',
  TAG_USER = 'tag.user',
}

export const APP_ACTION = {
  CREATE_NEW_POST: 'CREATE_NEW_POST'.toLowerCase(),
  CREATE_NEW_COMMENT: 'CREATE_NEW_COMMENT'.toLowerCase(),
  CREATE_POST_INTERACTION: 'CREATE_POST_INTERACTION'.toLowerCase(),
  UNDO_POST_INTERACTION: 'UNDO_POST_INTERACTION'.toLowerCase(),
  VIEW_POST_BY_ID: 'VIEW_POST_BY_ID'.toLowerCase(),
  VIEW_POST_BY_SLUG: 'VIEW_POST_BY_SLUG'.toLowerCase(),
  VIEW_POST_COMMENTS: 'VIEW_POST_COMMENTS'.toLowerCase(),
  RETWEET_POST: 'RETWEET_POST'.toLowerCase(),
  VIEW_USER_HOME_POSTS: 'VIEW_USER_HOME_POSTS'.toLowerCase(),
  VIEW_RECENT_POSTS: 'VIEW_RECENT_POSTS'.toLowerCase(),
  DELETE_POST_BY_SLUG: 'DELETE_POST_BY_SLUG'.toLowerCase(),
  GET_TWITTER_LOGIN_URL: 'GET_TWITTER_LOGIN_URL'.toLowerCase(),
  LOGIN_WITH_TWITTER: 'LOGIN_WITH_TWITTER'.toLowerCase(),
  REGISTER_WITH_EMAIL_PASSWORD: 'REGISTER_WITH_EMAIL_PASSWORD'.toLowerCase(),
  LOGIN_WITH_EMAIL_PASSWORD: 'LOGIN_WITH_EMAIL_PASSWORD'.toLowerCase(),
  GET_USER_PROFILE: 'GET_USER_PROFILE'.toLowerCase(),
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE'.toLowerCase(),
  UPDATE_USER_EMAIL: 'UPDATE_USER_EMAIL'.toLowerCase(),
  UPDATE_USER_IMAGE_URL: 'UPDATE_USER_IMAGE_URL'.toLowerCase(),
  UPDATE_USER_BANNER_URL: 'UPDATE_USER_BANNER_URL'.toLowerCase(),
  APPLY_REFERRAL_ADDRESS: 'APPLY_REFERRAL_ADDRESS'.toLowerCase(),
  PAGINATE_USER_TRADE_HISTORY: 'PAGINATE_USER_TRADE_HISTORY'.toLowerCase(),
  PAGINATE_RECENT_TRANSACTIONS: 'PAGINATE_RECENT_TRANSACTIONS'.toLowerCase(),
  BUY_SHARES: 'BUY_SHARES'.toLowerCase(),
  SELL_SHARES: 'SELL_SHARES'.toLowerCase(),
  FUNDS_TRANSFER: 'FUNDS_TRANSFER'.toLowerCase(),
  TRANSFER_TOKEN: 'TRANSFER_TOKEN'.toLowerCase(),
  GET_LIST_TOKEN_BALANCE: 'GET_LIST_TOKEN_BALANCE'.toLowerCase(),
  GET_TOKEN_BALANCE: 'GET_TOKEN_BALANCE'.toLowerCase(),
  VIEW_USER_EARNED_FEES: 'VIEW_USER_EARNED_FEES'.toLowerCase(),
  VIEW_SHARE_REPORT: 'VIEW_SHARE_REPORT'.toLowerCase(),
  VIEW_USER_RELATIONSHIPS: 'VIEW_USER_RELATIONSHIPS'.toLowerCase(),
  VIEW_USER_INFO: 'VIEW_USER_INFO'.toLowerCase(),
  VIEW_USER_INFO_BY_USER_NAME: 'VIEW_USER_INFO'.toLowerCase(),
  VIEW_INVESTMENT_INFO: 'VIEW_INVESTMENT_INFO'.toLowerCase(),
  PAGINATE_USER_POSTS: 'PAGINATE_USER_POSTS'.toLowerCase(),
  PAGINATE_WHO_TO_BUY: 'PAGINATE_WHO_TO_BUY'.toLowerCase(),
  PAGINATE_TOP_PROFILES: 'PAGINATE_TOP_PROFILES'.toLowerCase(),
  SEARCH_USERS: 'SEARCH_USERS'.toLowerCase(),
  SEARCH_TAG_USERS_AVAILABLE: 'SEARCH_TAG_USERS_AVAILABLE'.toLowerCase(),
  VIEW_USER_HOLDERS: 'VIEW_USER_HOLDERS'.toLowerCase(),
  VIEW_USER_HOLDINGS: 'VIEW_USER_HOLDINGS'.toLowerCase(),
  USER_SETUP_PIN: 'USER_SETUP_PIN'.toLowerCase(),
  USER_CHANGE_PIN: 'USER_CHANGE_PIN'.toLowerCase(),
  CREATE_NEW_VOTE: 'CREATE_NEW_VOTE'.toLowerCase(),
  VIEW_VOTE_INFO: 'VIEW_VOTE_INFO'.toLowerCase(),
  VIEW_TOTAL_UNCLAIMED: 'VIEW_TOTAL_UNCLAIMED'.toLowerCase(),
  PAGINATE_TOP_VOTES: 'PAGINATE_TOP_VOTES'.toLowerCase(),
  CREATE_NEW_FEEDBACK: 'CREATE_NEW_FEEDBACK'.toLowerCase(),
  PAGINATE_RECENT_FEEDBACKS: 'PAGINATE_RECENT_FEEDBACKS'.toLowerCase(),
  LOGIN_IN_TO_GAME: 'LOGIN_IN_TO_GAME'.toLowerCase(),
  CREATE_GAME_SESSION: 'CREATE_GAME_SESSION'.toLowerCase(),
  GET_IN_GAME_BALANCE: 'GET_IN_GAME_BALANCE'.toLowerCase(),
  GET_DEPOSIT_SETTING: 'GET_DEPOSIT_SETTING'.toLowerCase(),
  DEPOSIT_TO_GAME: 'DEPOSIT_TO_GAME'.toLowerCase(),
  WITHDRAW_FROM_GAME: 'WITHDRAW_FROM_GAME'.toLowerCase(),
  VIEW_DEPOSIT_HISTORY: 'VIEW_DEPOSIT_HISTORY'.toLowerCase(),
  VIEW_WITHDRAW_HISTORY: 'VIEW_WITHDRAW_HISTORY'.toLowerCase(),
  PUSH_NOTIFICATION: 'PUSH_NOTIFICATION'.toLowerCase(),
  REQUEST_TO_PUSH_NOTIFICATION: 'REQUEST_TO_PUSH_NOTIFICATION'.toLowerCase(),
  REQUEST_TO_CHECK_IMAGE_NSFW: 'REQUEST_TO_CHECK_IMAGE_NSFW'.toLowerCase(),
  VIEW_NOTIFICATIONS: 'VIEW_NOTIFICATIONS'.toLowerCase(),
  COUNT_UNREAD_NOTIFICATIONS: 'COUNT_UNREAD_NOTIFICATIONS'.toLowerCase(),
  READ_NOTIFICATIONS: 'READ_NOTIFICATIONS'.toLowerCase(),
  HANDLE_IMG_RESIZED_EVENT: 'HANDLE_IMG_RESIZED_EVENT'.toLowerCase(),
  CHECK_IS_AUGMENTLABS_USER_SIGNED_UP: 'CHECK_IS_AUGMENTLABS_USER_SIGNED_UP'.toLowerCase(),

  EXPORT_USER_PRIVATE_KEY: 'EXPORT_USER_PRIVATE_KEY'.toLowerCase(),
  PAGINATE_USER_CHATS: 'PAGINATE_USER_CHATS'.toLowerCase(),
  PAGINATE_CHAT_MESSAGES: 'PAGINATE_CHAT_MESSAGES'.toLowerCase(),
  VIEW_USER_CHAT_DETAIL: 'VIEW_USER_CHAT_DETAIL'.toLowerCase(),
  ADD_MESSAGE_TO_CHAT: 'ADD_MESSAGE_TO_CHAT'.toLowerCase(),
  SEND_CHAT_MESSAGE: 'SEND_CHAT_MESSAGE'.toLowerCase(),
  REPLY_CHAT_MESSAGE: 'REPLY_CHAT_MESSAGE'.toLowerCase(),
  MARK_MESSAGE_AS_READ: 'MARK_MESSAGE_AS_READ'.toLowerCase(),
  SEND_MESSAGE_TO_USER: 'SEND_MESSAGE_TO_USER'.toLowerCase(),
  CREATE_CHAT: 'CREATE_CHAT'.toLowerCase(),
  DELETE_MESSAGE: 'DELETE_MESSAGE'.toLowerCase(),
  GET_CHAT: 'GET_CHAT'.toLowerCase(),
  REMOVE_CHAT: 'REMOVE_CHAT'.toLowerCase(),
  POPULATE_CHAT_INFORMATION: 'POPULATE_CHAT_INFORMATION'.toLowerCase(),
  POPULATE_MESSAGE_INFORMATION: 'POPULATE_MESSAGE_INFORMATION'.toLowerCase(),
  COUNT_UNREAD_MESSAGES: 'COUNT_UNREAD_MESSAGES'.toLowerCase(),
  VIEW_POST_NOT_LIKE: 'VIEW_POST_NOT_LIKE'.toLowerCase(),
  VIEW_POST_NOT_COMMENT: 'VIEW_POST_NOT_COMMENT'.toLowerCase(),
  VIEW_POST_NEW_COMMENT: 'VIEW_POST_NEW_COMMENT'.toLowerCase(),

  //ADMIN_ACTIONS
  ADMIN_GET_LIST_USER: 'ADMIN_GET_LIST_USER'.toLowerCase(),
  ADMIN_GET_LIST_SYSTEM_ACCOUNT: 'ADMIN_GET_LIST_SYSTEM_ACCOUNT'.toLowerCase(),
  ADMIN_GET_USER_DETAIL: 'ADMIN_GET_USER_DETAIL'.toLowerCase(),
  ADMIN_UPDATE_USER_STATUS: 'ADMIN_UPDATE_USER_STATUS'.toLowerCase(),
  ADMIN_VIEW_TRANSACTION_HISTORY: 'ADMIN_VIEW_TRANSACTION_HISTORY'.toLowerCase(),
  ADMIN_EXPORT_INVESTMENT_SHARE_DATA: 'ADMIN_EXPORT_INVESTMENT_SHARE_DATA'.toLowerCase(),
  ADMIN_GET_INVESTMENT_REPORT: 'ADMIN_GET_INVESTMENT_REPORT'.toLowerCase(),
  ADMIN_UPDATE_USER_ACCOUNT_TYPE: 'ADMIN_UPDATE_USER_ACCOUNT_TYPE'.toLowerCase(),
  ADMIN_UPDATE_ACCOUNT_TYPE_CONFIG: 'ADMIN_UPDATE_ACCOUNT_TYPE_CONFIG'.toLowerCase(),
  ADMIN_BULK_UPDATE_ACCOUNT_TYPE_CONFIG: 'ADMIN_BULK_UPDATE_ACCOUNT_TYPE_CONFIG'.toLowerCase(),
  ADMIN_CHANGE_PASSWORD: 'ADMIN_CHANGE_PASSWORD'.toLowerCase(),
  ADMIN_GET_LIST_POST: 'ADMIN_GET_LIST_POST'.toLowerCase(),
  ADMIN_GET_POST_DETAIL: 'ADMIN_GET_POST_DETAIL'.toLowerCase(),
  ADMIN_DELETE_POST: 'ADMIN_DELETE_POST'.toLowerCase(),
  ADMIN_GET_LIST_FEEDBACK: 'ADMIN_GET_LIST_FEEDBACK'.toLowerCase(),
  ADMIN_LOGIN: 'ADMIN_LOGIN'.toLowerCase(),
  ADMIN_CREATE_NEW_SYSTEM_ACCOUNT_POST:
    'ADMIN_CREATE_NEW_SYSTEM_ACCOUNT_POST'.toLowerCase(),
};

export enum FEEDBACK_STATUS {
  SUBMITTED = 'submitted',
  SOLVED = 'solved',
  REJECTED = 'rejected',
}

export enum IMG_TASK_TYPE {
  USER_UPLOAD = 'user_upload',
}

export enum IMG_TASK_GOAL {
  RESIZE_AND_COMPRESS = 'RESIZE_AND_COMPRESS',
}

export enum IMAGE_SIZE {
  SMALL = 'small',
  MEDIUM = 'medium',
  LARGE = 'large',
}

export enum IMAGE_PROCESS_RESULT {
  PROCESSED = 'processed',
  REJECTED = 'rejected',
}

export enum SOURCE_TYPE {
  POST = 'post',
  MESSAGE = 'message',
}

export enum SOCIAL_TYPE {
  TWITTER = 'twitter',
  GOOGLE = 'google',
  EMAIL = 'email',
}

export enum EMAIL_TYPE {
  VERIFY_EMAIL = 'verify_email',
  RESET_PASSWORD = 'reset_password',
}
